const menuFood = [
  {
    id: 1,
    title: 'buttermilk',
    category: 'breakfast',
    price: 15.99,
    img: 'https://images.pexels.com/photos/70497/pexels-photo-70497.jpeg?auto=compress&cs=tinysrgb&w=600',
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
  },
  {
    id: 2,
    title: 'diner double',
    category: 'lunch',
    price: 13.99,
    img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQlf1JfasVusp62RFfj5R8uM-cabpX5zzEUhee-7Pgsfg&s',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 3,
    title: 'godzilla milkshake',
    category: 'shakes',
    price: 6.99,
    img: 'https://images.pexels.com/photos/103566/pexels-photo-103566.jpeg?auto=compress&cs=tinysrgb&w=600',
    desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
  },
  {
    id: 4,
    title: 'country delight',
    category: 'breakfast',
    price: 20.99,
    img: 'https://images.pexels.com/photos/4346305/pexels-photo-4346305.jpeg?auto=compress&cs=tinysrgb&w=600',
    desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
  },
  {
    id: 5,
    title: 'egg attack',
    category: 'lunch',
    price: 22.99,
    img: 'https://images.pexels.com/photos/16496268/pexels-photo-16496268/free-photo-of-breakfast-egg-on-toast.jpeg?auto=compress&cs=tinysrgb&w=600',
    desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
  },
  {
    id: 6,
    title: 'oreo dream',
    category: 'shakes',
    price: 18.99,
    img: 'https://images.pexels.com/photos/13922385/pexels-photo-13922385.jpeg?auto=compress&cs=tinysrgb&w=600',
    desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
  },
  {
    id: 7,
    title: 'bacon overflow',
    category: 'breakfast',
    price: 8.99,
    img: 'https://images.pexels.com/photos/17035133/pexels-photo-17035133/free-photo-of-fries-in-melted-cheese.jpeg?auto=compress&cs=tinysrgb&w=600',
    desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
  },
  {
    id: 8,
    title: 'american classic',
    category: 'lunch',
    price: 12.99,
    img: 'https://images.pexels.com/photos/13916440/pexels-photo-13916440.jpeg?auto=compress&cs=tinysrgb&w=600',
    desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
  },
  {
    id: 9,
    title: 'quarantine buddy',
    category: 'shakes',
    price: 16.99,
    img: 'https://images.pexels.com/photos/4057736/pexels-photo-4057736.jpeg?auto=compress&cs=tinysrgb&w=600',
    desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
  },
  {
    id: 10,
    title: 'Waffles',
    category: 'diner',
    price: 20.85,
    img: 'https://images.pexels.com/photos/5377444/pexels-photo-5377444.jpeg?auto=compress&cs=tinysrgb&w=600',
    desc: `Waffles are a breakfast staple–whether you throw them in the toaster at home or order them from your favorite diner.  `,
  },
  {
    id: 11,
    title: ' Reuben diner',
    category: 'diner',
    price: 35.05,
    img: 'https://media.istockphoto.com/id/187215954/photo/reuben-sandwich-close-up.jpg?b=1&s=612x612&w=0&k=20&c=79S2g7JzMWVyeYP53tTUV8QdDzJUiwBmWeCEcU2fnFU=',
    desc: `here's nothing quite like a milkshake to help you cool off while also getting a bit of a sweet treat.`,
  },
  {
    id: 12,
    title: 'Eton Mess ice cream',
    category: 'shakes',
    price: 16.99,
    img: 'https://images.pexels.com/photos/327131/pexels-photo-327131.jpeg?auto=compress&cs=tinysrgb&w=600',
    desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
  },
];
export default menuFood;